### PR TITLE
Suppress serial version uuid error

### PR DESCRIPTION
**Pull request by willyborankin**
Suppress serial version uuid error message during compilation.

### CODE REVIEW

**Comment by ivanyu** [comment]
I now realize why you tried to add `serialVersionUID` - to make the compiler happy. I think, this was a better way than suppressing the whole error.

**Comment by willyborankin** [comment]
> I now realize why you tried to add `serialVersionUID` - to make the compiler happy. I think, this was a better way than suppressing the whole error.

Will add generated on ;-) instead of 1L. 1L is a bad practice

**Comment by ivanyu** [comment]
1L is totally fine, btw :)

**Comment by willyborankin** [comment]
close it since https://github.com/aiven/aiven-kafka-auth/pull/16 was opened as a replacement

**Pull request closed without merging**
